name: test

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]


jobs:
  install-test:
    name: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: run tests
      run: make ci
